// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: protos/internal.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// PubsubState is for serializing a snapshot of known topics and peers
// to the Store without having to persist it on a proper append-only
// PLAN channel. This is internal to the Vault.
type PubsubState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topics []*TopicPointer `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
	Peers  []*Peer         `protobuf:"bytes,2,rep,name=Peers,proto3" json:"Peers,omitempty"`
}

func (x *PubsubState) Reset() {
	*x = PubsubState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_internal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubsubState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubsubState) ProtoMessage() {}

func (x *PubsubState) ProtoReflect() protoreflect.Message {
	mi := &file_protos_internal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubsubState.ProtoReflect.Descriptor instead.
func (*PubsubState) Descriptor() ([]byte, []int) {
	return file_protos_internal_proto_rawDescGZIP(), []int{0}
}

func (x *PubsubState) GetTopics() []*TopicPointer {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *PubsubState) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type TopicPointer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                 string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	LastEntryPublished []byte `protobuf:"bytes,2,opt,name=LastEntryPublished,proto3" json:"LastEntryPublished,omitempty"`
}

func (x *TopicPointer) Reset() {
	*x = TopicPointer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_internal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicPointer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPointer) ProtoMessage() {}

func (x *TopicPointer) ProtoReflect() protoreflect.Message {
	mi := &file_protos_internal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPointer.ProtoReflect.Descriptor instead.
func (*TopicPointer) Descriptor() ([]byte, []int) {
	return file_protos_internal_proto_rawDescGZIP(), []int{1}
}

func (x *TopicPointer) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *TopicPointer) GetLastEntryPublished() []byte {
	if x != nil {
		return x.LastEntryPublished
	}
	return nil
}

var File_protos_internal_proto protoreflect.FileDescriptor

var file_protos_internal_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x1a, 0x12,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x0b, 0x50, 0x75, 0x62, 0x73, 0x75, 0x62, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x2b, 0x0a, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x12, 0x21,
	0x0a, 0x05, 0x50, 0x65, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x05, 0x50, 0x65, 0x65, 0x72,
	0x73, 0x22, 0x4e, 0x0a, 0x0c, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x2e, 0x0a, 0x12, 0x4c, 0x61, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x12, 0x4c,
	0x61, 0x73, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x65,
	0x64, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x70, 0x6c, 0x61, 0x6e, 0x2d, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x2f, 0x70, 0x6c, 0x61,
	0x6e, 0x2d, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2d, 0x6c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_internal_proto_rawDescOnce sync.Once
	file_protos_internal_proto_rawDescData = file_protos_internal_proto_rawDesc
)

func file_protos_internal_proto_rawDescGZIP() []byte {
	file_protos_internal_proto_rawDescOnce.Do(func() {
		file_protos_internal_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_internal_proto_rawDescData)
	})
	return file_protos_internal_proto_rawDescData
}

var file_protos_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_internal_proto_goTypes = []interface{}{
	(*PubsubState)(nil),  // 0: vault.PubsubState
	(*TopicPointer)(nil), // 1: vault.TopicPointer
	(*Peer)(nil),         // 2: vault.Peer
}
var file_protos_internal_proto_depIdxs = []int32{
	1, // 0: vault.PubsubState.Topics:type_name -> vault.TopicPointer
	2, // 1: vault.PubsubState.Peers:type_name -> vault.Peer
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_internal_proto_init() }
func file_protos_internal_proto_init() {
	if File_protos_internal_proto != nil {
		return
	}
	file_protos_vault_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protos_internal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubsubState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_internal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicPointer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_internal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_internal_proto_goTypes,
		DependencyIndexes: file_protos_internal_proto_depIdxs,
		MessageInfos:      file_protos_internal_proto_msgTypes,
	}.Build()
	File_protos_internal_proto = out.File
	file_protos_internal_proto_rawDesc = nil
	file_protos_internal_proto_goTypes = nil
	file_protos_internal_proto_depIdxs = nil
}
