// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: protos/vault.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Const int32

const (
	Const_ConstDefs Const = 0
	// EntryIDSz is the expected byte size of an EntryID
	Const_EntryIDSz Const = 30
	// DefaultGrpcServicePort is the TCP port number that the service VaultGrpc should run on by default.
	Const_DefaultGrpcServicePort Const = 5190
)

// Enum value maps for Const.
var (
	Const_name = map[int32]string{
		0:    "ConstDefs",
		30:   "EntryIDSz",
		5190: "DefaultGrpcServicePort",
	}
	Const_value = map[string]int32{
		"ConstDefs":              0,
		"EntryIDSz":              30,
		"DefaultGrpcServicePort": 5190,
	}
)

func (x Const) Enum() *Const {
	p := new(Const)
	*p = x
	return p
}

func (x Const) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Const) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vault_proto_enumTypes[0].Descriptor()
}

func (Const) Type() protoreflect.EnumType {
	return &file_protos_vault_proto_enumTypes[0]
}

func (x Const) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Const.Descriptor instead.
func (Const) EnumDescriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{0}
}

// ReqOp is a code describing the purpose and format of the vault Req that it resides in.
type ReqOp int32

const (
	ReqOp_InvalidEntry ReqOp = 0
	// AppendEntry requests that FeedReq.NewEntry is appended to the given stream URI.
	// When this entry has been committed, a ReqComplete will be returned.
	ReqOp_AppendEntry ReqOp = 1
	// ChannelGenesis creates a new channel specified in FeedReq.FeedURI
	// FeedReq.NewEntry is written into the new channel (and is the channel genesis entry).
	ReqOp_ChannelGenesis ReqOp = 2
	// CancelReq tells the server to cancel/stop/close the request identified by the given ReqID.
	// Unlike all other client-to-server requests, the ReqID of this msg is not newly issued -- it refers to an existing request.
	ReqOp_CancelReq ReqOp = 10
	// OpenFeed requests to open a given channel feed based on the params in FeedReq.OpenFeed
	// On success, the server does not send a response and either begins streaming (if it was requested) and/or awaits requests for channel feed.
	ReqOp_OpenFeed ReqOp = 30
)

// Enum value maps for ReqOp.
var (
	ReqOp_name = map[int32]string{
		0:  "InvalidEntry",
		1:  "AppendEntry",
		2:  "ChannelGenesis",
		10: "CancelReq",
		30: "OpenFeed",
	}
	ReqOp_value = map[string]int32{
		"InvalidEntry":   0,
		"AppendEntry":    1,
		"ChannelGenesis": 2,
		"CancelReq":      10,
		"OpenFeed":       30,
	}
)

func (x ReqOp) Enum() *ReqOp {
	p := new(ReqOp)
	*p = x
	return p
}

func (x ReqOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReqOp) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vault_proto_enumTypes[1].Descriptor()
}

func (ReqOp) Type() protoreflect.EnumType {
	return &file_protos_vault_proto_enumTypes[1]
}

func (x ReqOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReqOp.Descriptor instead.
func (ReqOp) EnumDescriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{1}
}

// MsgOp tells a holder of a Msg how to interpret its fields.
// On general this is how a Vault communicates to a client.
type MsgOp int32

const (
	// FeedEntry delivers the next entry in a feed stream identified by FeedMsg.ReqID.
	MsgOp_FeedEntry MsgOp = 0
	// ReqComplete means the referenced request (via FeedMsg.ReqID) has successfully completed.
	// Other values in the FeedMsg are contextual the op that was completed.
	MsgOp_ReqComplete MsgOp = 1
	// ReqDiscarded means the referenced request failed and/or has been cancelled.
	// If Msg.Body != nil, then it is a serialized ReqErr describing why it was discarded.
	// As with ReqComplete, the referenced request is now closed/complete, so the given ReqID is now available for (re)use.
	MsgOp_ReqDiscarded MsgOp = 3
	// FeedReqStatus is the server reporting progress for the given ReqID.
	// FeedMsg.Body is a serialized ReqStatus.
	MsgOp_FeedReqStatus MsgOp = 4
)

// Enum value maps for MsgOp.
var (
	MsgOp_name = map[int32]string{
		0: "FeedEntry",
		1: "ReqComplete",
		3: "ReqDiscarded",
		4: "FeedReqStatus",
	}
	MsgOp_value = map[string]int32{
		"FeedEntry":     0,
		"ReqComplete":   1,
		"ReqDiscarded":  3,
		"FeedReqStatus": 4,
	}
)

func (x MsgOp) Enum() *MsgOp {
	p := new(MsgOp)
	*p = x
	return p
}

func (x MsgOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgOp) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vault_proto_enumTypes[2].Descriptor()
}

func (MsgOp) Type() protoreflect.EnumType {
	return &file_protos_vault_proto_enumTypes[2]
}

func (x MsgOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgOp.Descriptor instead.
func (MsgOp) EnumDescriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{2}
}

type StreamMode int32

const (
	// DontStream means the server should not stream any entries.
	// This mode is typically used by clients that only want to append
	// entries to a feed.  SeekEntryID is ignored.
	StreamMode_DontStream StreamMode = 0
	// FromGenesis tells the server to start streaming from the very
	// beginning of the feed.  SeekEntryID is ignored.
	StreamMode_FromGenesis StreamMode = 1
	// AtEntry tells the server to stream starting with SeekEntryID.
	StreamMode_AtEntry StreamMode = 4
	// AfterEntry tells the server to stream starting with the entry
	// immediately *after* SeekEntryID.
	StreamMode_AfterEntry StreamMode = 5
	// AfterHead tells the server to resume after the latest entry in this feed.
	// SeekEntryID is ignored.
	StreamMode_AfterHead StreamMode = 7
	// FromIndex tells the server to treat stream entries in order of
	// arrival at this vault peer, rather than ordered by
	// EntryID. This allows clients to catch up to entries received
	// while they were offline. The SeekEntryID is treated as the
	// index.
	StreamMode_FromIndex StreamMode = 9
)

// Enum value maps for StreamMode.
var (
	StreamMode_name = map[int32]string{
		0: "DontStream",
		1: "FromGenesis",
		4: "AtEntry",
		5: "AfterEntry",
		7: "AfterHead",
		9: "FromIndex",
	}
	StreamMode_value = map[string]int32{
		"DontStream":  0,
		"FromGenesis": 1,
		"AtEntry":     4,
		"AfterEntry":  5,
		"AfterHead":   7,
		"FromIndex":   9,
	}
)

func (x StreamMode) Enum() *StreamMode {
	p := new(StreamMode)
	*p = x
	return p
}

func (x StreamMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamMode) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vault_proto_enumTypes[3].Descriptor()
}

func (StreamMode) Type() protoreflect.EnumType {
	return &file_protos_vault_proto_enumTypes[3]
}

func (x StreamMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamMode.Descriptor instead.
func (StreamMode) EnumDescriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{3}
}

// StatusCode expresses milestones for a given feed request.
type StatusCode int32

const (
	// InfoMsg means there is no status change, other than the amplifying message in ReqStatus.Msg
	StatusCode_InfoMsg StatusCode = 0
	// WarningMsg means there is no status change, other than the warning message in ReqStatus.Msg.
	StatusCode_WarningMsg StatusCode = 1
	// Working is a flag that means that the request is actively being worked and to expect progress on the order of several seconds.
	StatusCode_Working           StatusCode = 64
	StatusCode_FindingPeers      StatusCode = 65
	StatusCode_ConnectingToPeers StatusCode = 66
	StatusCode_SearchingForFeed  StatusCode = 67
	StatusCode_TransferringFeed  StatusCode = 68
	// Stalled is a flag that means the request is in a long-term wait state of some kind with an unbounded completion time.
	// This flag can be ORed to any of the above "Working" status code values.
	StatusCode_Stalled StatusCode = 128
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:   "InfoMsg",
		1:   "WarningMsg",
		64:  "Working",
		65:  "FindingPeers",
		66:  "ConnectingToPeers",
		67:  "SearchingForFeed",
		68:  "TransferringFeed",
		128: "Stalled",
	}
	StatusCode_value = map[string]int32{
		"InfoMsg":           0,
		"WarningMsg":        1,
		"Working":           64,
		"FindingPeers":      65,
		"ConnectingToPeers": 66,
		"SearchingForFeed":  67,
		"TransferringFeed":  68,
		"Stalled":           128,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vault_proto_enumTypes[4].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_protos_vault_proto_enumTypes[4]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{4}
}

// ErrCode is used to unambiguously express common errors.
type ErrCode int32

const (
	ErrCode_NoErr                   ErrCode = 0
	ErrCode_UnnamedErr              ErrCode = 5000
	ErrCode_ReqCanceled             ErrCode = 5001
	ErrCode_InsufficientPermissions ErrCode = 5101
	ErrCode_ReqNotFound             ErrCode = 5010
	ErrCode_ReqInUse                ErrCode = 5011
	ErrCode_InvalidFeedURI          ErrCode = 5020
	ErrCode_FeedNotFound            ErrCode = 5021
	ErrCode_FeedAlreadyExists       ErrCode = 5022
	ErrCode_UnrecognizedVaultCtx    ErrCode = 5030
	ErrCode_InvalidRequest          ErrCode = 5040
	ErrCode_DatabaseError           ErrCode = 6000
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "NoErr",
		5000: "UnnamedErr",
		5001: "ReqCanceled",
		5101: "InsufficientPermissions",
		5010: "ReqNotFound",
		5011: "ReqInUse",
		5020: "InvalidFeedURI",
		5021: "FeedNotFound",
		5022: "FeedAlreadyExists",
		5030: "UnrecognizedVaultCtx",
		5040: "InvalidRequest",
		6000: "DatabaseError",
	}
	ErrCode_value = map[string]int32{
		"NoErr":                   0,
		"UnnamedErr":              5000,
		"ReqCanceled":             5001,
		"InsufficientPermissions": 5101,
		"ReqNotFound":             5010,
		"ReqInUse":                5011,
		"InvalidFeedURI":          5020,
		"FeedNotFound":            5021,
		"FeedAlreadyExists":       5022,
		"UnrecognizedVaultCtx":    5030,
		"InvalidRequest":          5040,
		"DatabaseError":           6000,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vault_proto_enumTypes[5].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_protos_vault_proto_enumTypes[5]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{5}
}

// PeerUpdateOp tells us what to do with the Peer we just got. Note
// that we only remove a peer ID when it's gone permanently, not when
// it's temporarily unavailable or has moved to a new multiaddr.
type PeerUpdateOp int32

const (
	PeerUpdateOp_Nothing           PeerUpdateOp = 0 // stored state representation
	PeerUpdateOp_Upsert            PeerUpdateOp = 10
	PeerUpdateOp_RemovePermanently PeerUpdateOp = 20
)

// Enum value maps for PeerUpdateOp.
var (
	PeerUpdateOp_name = map[int32]string{
		0:  "Nothing",
		10: "Upsert",
		20: "RemovePermanently",
	}
	PeerUpdateOp_value = map[string]int32{
		"Nothing":           0,
		"Upsert":            10,
		"RemovePermanently": 20,
	}
)

func (x PeerUpdateOp) Enum() *PeerUpdateOp {
	p := new(PeerUpdateOp)
	*p = x
	return p
}

func (x PeerUpdateOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerUpdateOp) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_vault_proto_enumTypes[6].Descriptor()
}

func (PeerUpdateOp) Type() protoreflect.EnumType {
	return &file_protos_vault_proto_enumTypes[6]
}

func (x PeerUpdateOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerUpdateOp.Descriptor instead.
func (PeerUpdateOp) EnumDescriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{6}
}

type FeedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ReqOp requests that the given op to be execute on ChReq.Entries
	ReqOp ReqOp `protobuf:"varint,1,opt,name=ReqOp,proto3,enum=vault.ReqOp" json:"ReqOp,omitempty"`
	// ReqID is a client-assigned ID that allows the client and server to reference this ChReq in the future.
	// Node.ReqComplete & ReqDiscarded is how the server signals when this request is considered closed/complete.
	ReqID int32 `protobuf:"varint,2,opt,name=ReqID,proto3" json:"ReqID,omitempty"`
	// OpenFeed opens a feed for access.
	OpenFeed *OpenFeedReq `protobuf:"bytes,10,opt,name=OpenFeed,proto3" json:"OpenFeed,omitempty"`
	// NewEntry is contains an entry to be appended to this feed.
	// If non-nil, FeedURI should be created and this entry should be the first entry appended to it.
	NewEntry *Msg `protobuf:"bytes,20,opt,name=NewEntry,proto3" json:"NewEntry,omitempty"`
}

func (x *FeedReq) Reset() {
	*x = FeedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vault_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedReq) ProtoMessage() {}

func (x *FeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vault_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedReq.ProtoReflect.Descriptor instead.
func (*FeedReq) Descriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{0}
}

func (x *FeedReq) GetReqOp() ReqOp {
	if x != nil {
		return x.ReqOp
	}
	return ReqOp_InvalidEntry
}

func (x *FeedReq) GetReqID() int32 {
	if x != nil {
		return x.ReqID
	}
	return 0
}

func (x *FeedReq) GetOpenFeed() *OpenFeedReq {
	if x != nil {
		return x.OpenFeed
	}
	return nil
}

func (x *FeedReq) GetNewEntry() *Msg {
	if x != nil {
		return x.NewEntry
	}
	return nil
}

type OpenFeedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// FeedURI is the feed name to be opened.
	// A feed URI a case-sensitive, UTF8, POSIX-style pathname.
	FeedURI string `protobuf:"bytes,10,opt,name=FeedURI,proto3" json:"FeedURI,omitempty"`
	// StreamMode specifies if and where the server should start streaming feed entries.
	StreamMode StreamMode `protobuf:"varint,11,opt,name=StreamMode,proto3,enum=vault.StreamMode" json:"StreamMode,omitempty"`
	// SeekEntryID tells the server where to start streaming.
	SeekEntryID []byte `protobuf:"bytes,12,opt,name=SeekEntryID,proto3" json:"SeekEntryID,omitempty"`
	// MaxEntriesToSend limits the number of entries the server will stream.
	// If 0, then no limit is set.
	MaxEntriesToSend int32 `protobuf:"varint,13,opt,name=MaxEntriesToSend,proto3" json:"MaxEntriesToSend,omitempty"`
	// SendEntryIDsOnly tells the server to only send EntryIDs (MsgData and MsgCodec will be nil)
	SendEntryIDsOnly bool `protobuf:"varint,14,opt,name=SendEntryIDsOnly,proto3" json:"SendEntryIDsOnly,omitempty"`
}

func (x *OpenFeedReq) Reset() {
	*x = OpenFeedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vault_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenFeedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFeedReq) ProtoMessage() {}

func (x *OpenFeedReq) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vault_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFeedReq.ProtoReflect.Descriptor instead.
func (*OpenFeedReq) Descriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{1}
}

func (x *OpenFeedReq) GetFeedURI() string {
	if x != nil {
		return x.FeedURI
	}
	return ""
}

func (x *OpenFeedReq) GetStreamMode() StreamMode {
	if x != nil {
		return x.StreamMode
	}
	return StreamMode_DontStream
}

func (x *OpenFeedReq) GetSeekEntryID() []byte {
	if x != nil {
		return x.SeekEntryID
	}
	return nil
}

func (x *OpenFeedReq) GetMaxEntriesToSend() int32 {
	if x != nil {
		return x.MaxEntriesToSend
	}
	return 0
}

func (x *OpenFeedReq) GetSendEntryIDsOnly() bool {
	if x != nil {
		return x.SendEntryIDsOnly
	}
	return false
}

type EntryHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// EntryID names the entry being posted and is a binary ID based on a hash of the entry body.
	// The vault can safely assume that no two entries will ever share the same EntryID.
	// The expected byte size of this ID (and all other entry IDs is Const.EntryIDSz)
	EntryID []byte `protobuf:"bytes,1,opt,name=EntryID,proto3" json:"EntryID,omitempty"`
	// MemberID tells us what key signed the entry.
	MemberID []byte `protobuf:"bytes,2,opt,name=MemberID,proto3" json:"MemberID,omitempty"`
	// ParentID names a parent of this entry and intended to be an aid for a vault to help find and recover missing entries in a feed.
	ParentID []byte `protobuf:"bytes,10,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	// EntryCodec is a POSIX-style pathname that describes the encoding of this entry's data body.
	// It is not needed/used by the vault (with the exception that vaults may insert entries into a feed stream to meta-communicate).
	// Unrecognized codec types should be ignored but passed on as applicable.
	EntryCodec string `protobuf:"bytes,11,opt,name=EntryCodec,proto3" json:"EntryCodec,omitempty"`
	// FeedURI tells the client what Channel the Entry is associated with.
	FeedURI string `protobuf:"bytes,15,opt,name=FeedURI,proto3" json:"FeedURI,omitempty"`
}

func (x *EntryHeader) Reset() {
	*x = EntryHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vault_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryHeader) ProtoMessage() {}

func (x *EntryHeader) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vault_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryHeader.ProtoReflect.Descriptor instead.
func (*EntryHeader) Descriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{2}
}

func (x *EntryHeader) GetEntryID() []byte {
	if x != nil {
		return x.EntryID
	}
	return nil
}

func (x *EntryHeader) GetMemberID() []byte {
	if x != nil {
		return x.MemberID
	}
	return nil
}

func (x *EntryHeader) GetParentID() []byte {
	if x != nil {
		return x.ParentID
	}
	return nil
}

func (x *EntryHeader) GetEntryCodec() string {
	if x != nil {
		return x.EntryCodec
	}
	return ""
}

func (x *EntryHeader) GetFeedURI() string {
	if x != nil {
		return x.FeedURI
	}
	return ""
}

// Msg is the generalized response object that a vault sends to the client as it processes each requests sent by the client.
type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// MsOp tells the client how to interpret the fields in this FeedMsg.
	Op MsgOp `protobuf:"varint,1,opt,name=Op,proto3,enum=vault.MsgOp" json:"Op,omitempty"`
	// ReqID is set to value the originating FeedReq.ReqID was set to.
	ReqID int32 `protobuf:"varint,2,opt,name=ReqID,proto3" json:"ReqID,omitempty"`
	// EntryHeader, if non-nil, provides info about the entry contained in Msg.Body.
	EntryHeader *EntryHeader `protobuf:"bytes,8,opt,name=EntryHeader,proto3" json:"EntryHeader,omitempty"`
	// Body is an entry's data body
	Body []byte `protobuf:"bytes,10,opt,name=Body,proto3" json:"Body,omitempty"`
	// Status provides status information about the request beyond
	// what is provided in thenMsgOp
	Status *ReqStatus `protobuf:"bytes,20,opt,name=Status,proto3" json:"Status,omitempty"`
	// Err provides details about error conditions.
	Err *ReqErr `protobuf:"bytes,30,opt,name=Err,proto3" json:"Err,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vault_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vault_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{3}
}

func (x *Msg) GetOp() MsgOp {
	if x != nil {
		return x.Op
	}
	return MsgOp_FeedEntry
}

func (x *Msg) GetReqID() int32 {
	if x != nil {
		return x.ReqID
	}
	return 0
}

func (x *Msg) GetEntryHeader() *EntryHeader {
	if x != nil {
		return x.EntryHeader
	}
	return nil
}

func (x *Msg) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Msg) GetStatus() *ReqStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Msg) GetErr() *ReqErr {
	if x != nil {
		return x.Err
	}
	return nil
}

// ReqStatus is used in conjunction with FeedMsgOp.StatusUpdate and expresses milestones for a given client request.
type ReqStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ReqID is feed request ID that this update is reporting about.
	ReqID int32 `protobuf:"varint,1,opt,name=ReqID,proto3" json:"ReqID,omitempty"`
	// Code describes the status of ReqID.
	Code StatusCode `protobuf:"varint,2,opt,name=Code,proto3,enum=vault.StatusCode" json:"Code,omitempty"`
	// Msg is an optional human-readable message describing the current status of a request.
	Msg string `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
	// If applicable this is a relevant entry ID.
	EntryID []byte `protobuf:"bytes,4,opt,name=EntryID,proto3" json:"EntryID,omitempty"`
	// If greater than zero, these are estimates of the work or time remaining.
	BytesRemaining int64 `protobuf:"varint,10,opt,name=BytesRemaining,proto3" json:"BytesRemaining,omitempty"`
	SecsRemaining  int64 `protobuf:"varint,11,opt,name=SecsRemaining,proto3" json:"SecsRemaining,omitempty"`
}

func (x *ReqStatus) Reset() {
	*x = ReqStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vault_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqStatus) ProtoMessage() {}

func (x *ReqStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vault_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqStatus.ProtoReflect.Descriptor instead.
func (*ReqStatus) Descriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{4}
}

func (x *ReqStatus) GetReqID() int32 {
	if x != nil {
		return x.ReqID
	}
	return 0
}

func (x *ReqStatus) GetCode() StatusCode {
	if x != nil {
		return x.Code
	}
	return StatusCode_InfoMsg
}

func (x *ReqStatus) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ReqStatus) GetEntryID() []byte {
	if x != nil {
		return x.EntryID
	}
	return nil
}

func (x *ReqStatus) GetBytesRemaining() int64 {
	if x != nil {
		return x.BytesRemaining
	}
	return 0
}

func (x *ReqStatus) GetSecsRemaining() int64 {
	if x != nil {
		return x.SecsRemaining
	}
	return 0
}

// ReqErr wraps any error and is typically used in conjunction with FeedMsgOp.ReqDiscarded
type ReqErr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ErrCode `protobuf:"varint,1,opt,name=Code,proto3,enum=vault.ErrCode" json:"Code,omitempty"`
	Msg  string  `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *ReqErr) Reset() {
	*x = ReqErr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vault_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqErr) ProtoMessage() {}

func (x *ReqErr) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vault_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqErr.ProtoReflect.Descriptor instead.
func (*ReqErr) Descriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{5}
}

func (x *ReqErr) GetCode() ErrCode {
	if x != nil {
		return x.Code
	}
	return ErrCode_NoErr
}

func (x *ReqErr) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// PubsubState is for serializing a snapshot of known topics and peers
// to the Store without having to persist it on a proper append-only
// PLAN channel. This is internal to the Vault.
type PubsubState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topics []string `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
	Peers  []*Peer  `protobuf:"bytes,2,rep,name=Peers,proto3" json:"Peers,omitempty"`
}

func (x *PubsubState) Reset() {
	*x = PubsubState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vault_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubsubState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubsubState) ProtoMessage() {}

func (x *PubsubState) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vault_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubsubState.ProtoReflect.Descriptor instead.
func (*PubsubState) Descriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{6}
}

func (x *PubsubState) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *PubsubState) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

// Peer is the body of a message sent over the discovery Channel for
// sharing peer network addresses and public keys.
type Peer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Op tells us what to do with this
	Op PeerUpdateOp `protobuf:"varint,1,opt,name=Op,proto3,enum=vault.PeerUpdateOp" json:"Op,omitempty"`
	// ID is the Peer ID
	ID string `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	// Key is the Peer public key
	Key []byte `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	// multiaddrs is the list of network multiaddresses for this peer
	Multiaddrs [][]byte `protobuf:"bytes,5,rep,name=Multiaddrs,proto3" json:"Multiaddrs,omitempty"`
}

func (x *Peer) Reset() {
	*x = Peer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_vault_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_protos_vault_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_protos_vault_proto_rawDescGZIP(), []int{7}
}

func (x *Peer) GetOp() PeerUpdateOp {
	if x != nil {
		return x.Op
	}
	return PeerUpdateOp_Nothing
}

func (x *Peer) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Peer) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Peer) GetMultiaddrs() [][]byte {
	if x != nil {
		return x.Multiaddrs
	}
	return nil
}

var File_protos_vault_proto protoreflect.FileDescriptor

var file_protos_vault_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x07,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x12, 0x22, 0x0a, 0x05, 0x52, 0x65, 0x71, 0x4f, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x52,
	0x65, 0x71, 0x4f, 0x70, 0x52, 0x05, 0x52, 0x65, 0x71, 0x4f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x52,
	0x65, 0x71, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x65, 0x71, 0x49,
	0x44, 0x12, 0x2e, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x65, 0x65, 0x64, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x4f, 0x70, 0x65, 0x6e,
	0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x52, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x65, 0x65,
	0x64, 0x12, 0x26, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x14, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x52,
	0x08, 0x4e, 0x65, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x22, 0xd4, 0x01, 0x0a, 0x0b, 0x4f, 0x70,
	0x65, 0x6e, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x65, 0x65,
	0x64, 0x55, 0x52, 0x49, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x65, 0x65, 0x64,
	0x55, 0x52, 0x49, 0x12, 0x31, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x6f, 0x64,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x65, 0x65, 0x6b, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x49, 0x44, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x53, 0x65, 0x65,
	0x6b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x44, 0x12, 0x2a, 0x0a, 0x10, 0x4d, 0x61, 0x78, 0x45,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x54, 0x6f, 0x53, 0x65, 0x6e, 0x64, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x10, 0x4d, 0x61, 0x78, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x54, 0x6f,
	0x53, 0x65, 0x6e, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x49, 0x44, 0x73, 0x4f, 0x6e, 0x6c, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10,
	0x53, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x44, 0x73, 0x4f, 0x6e, 0x6c, 0x79,
	0x22, 0x99, 0x01, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x63,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x46, 0x65, 0x65, 0x64, 0x55, 0x52, 0x49, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x46, 0x65, 0x65, 0x64, 0x55, 0x52, 0x49, 0x22, 0xce, 0x01, 0x0a,
	0x03, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x02, 0x4f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0c, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x4f, 0x70, 0x52, 0x02,
	0x4f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x71, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x52, 0x65, 0x71, 0x49, 0x44, 0x12, 0x34, 0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x0b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x42, 0x6f,
	0x64, 0x79, 0x12, 0x28, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x14, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x03,
	0x45, 0x72, 0x72, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x76, 0x61, 0x75, 0x6c,
	0x74, 0x2e, 0x52, 0x65, 0x71, 0x45, 0x72, 0x72, 0x52, 0x03, 0x45, 0x72, 0x72, 0x22, 0xc2, 0x01,
	0x0a, 0x09, 0x52, 0x65, 0x71, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x52,
	0x65, 0x71, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x52, 0x65, 0x71, 0x49,
	0x44, 0x12, 0x25, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x6d,
	0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x24, 0x0a, 0x0d,
	0x53, 0x65, 0x63, 0x73, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x53, 0x65, 0x63, 0x73, 0x52, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x22, 0x3e, 0x0a, 0x06, 0x52, 0x65, 0x71, 0x45, 0x72, 0x72, 0x12, 0x22, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x76, 0x61, 0x75,
	0x6c, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x22, 0x48, 0x0a, 0x0b, 0x50, 0x75, 0x62, 0x73, 0x75, 0x62, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x50, 0x65, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74,
	0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x05, 0x50, 0x65, 0x65, 0x72, 0x73, 0x22, 0x6d, 0x0a, 0x04,
	0x50, 0x65, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x02, 0x4f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4f, 0x70, 0x52, 0x02, 0x4f, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x61, 0x64, 0x64, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52,
	0x0a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x61, 0x64, 0x64, 0x72, 0x73, 0x2a, 0x42, 0x0a, 0x05, 0x43,
	0x6f, 0x6e, 0x73, 0x74, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x44, 0x65, 0x66,
	0x73, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x49, 0x44, 0x53, 0x7a,
	0x10, 0x1e, 0x12, 0x1b, 0x0a, 0x16, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x47, 0x72, 0x70,
	0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x10, 0xc6, 0x28, 0x2a,
	0x5b, 0x0a, 0x05, 0x52, 0x65, 0x71, 0x4f, 0x70, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x6e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x70,
	0x70, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x47, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x10, 0x02, 0x12,
	0x0d, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x10, 0x0a, 0x12, 0x0c,
	0x0a, 0x08, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x65, 0x65, 0x64, 0x10, 0x1e, 0x2a, 0x4c, 0x0a, 0x05,
	0x4d, 0x73, 0x67, 0x4f, 0x70, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x65, 0x65, 0x64, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x44, 0x69, 0x73, 0x63,
	0x61, 0x72, 0x64, 0x65, 0x64, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x65, 0x65, 0x64, 0x52,
	0x65, 0x71, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x10, 0x04, 0x2a, 0x68, 0x0a, 0x0a, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x6f, 0x6e, 0x74,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x46, 0x72, 0x6f, 0x6d,
	0x47, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x74, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x66, 0x74, 0x65, 0x72, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x66, 0x74, 0x65, 0x72, 0x48,
	0x65, 0x61, 0x64, 0x10, 0x07, 0x12, 0x0d, 0x0a, 0x09, 0x46, 0x72, 0x6f, 0x6d, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x10, 0x09, 0x2a, 0x99, 0x01, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x73, 0x67, 0x10, 0x00,
	0x12, 0x0e, 0x0a, 0x0a, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4d, 0x73, 0x67, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x57, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x10, 0x40, 0x12, 0x10, 0x0a,
	0x0c, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x65, 0x65, 0x72, 0x73, 0x10, 0x41, 0x12,
	0x15, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x50,
	0x65, 0x65, 0x72, 0x73, 0x10, 0x42, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x69, 0x6e, 0x67, 0x46, 0x6f, 0x72, 0x46, 0x65, 0x65, 0x64, 0x10, 0x43, 0x12, 0x14, 0x0a, 0x10,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x72, 0x69, 0x6e, 0x67, 0x46, 0x65, 0x65, 0x64,
	0x10, 0x44, 0x12, 0x0c, 0x0a, 0x07, 0x53, 0x74, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x10, 0x80, 0x01,
	0x2a, 0xfa, 0x01, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x09, 0x0a, 0x05,
	0x4e, 0x6f, 0x45, 0x72, 0x72, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0a, 0x55, 0x6e, 0x6e, 0x61, 0x6d,
	0x65, 0x64, 0x45, 0x72, 0x72, 0x10, 0x88, 0x27, 0x12, 0x10, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x43,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x65, 0x64, 0x10, 0x89, 0x27, 0x12, 0x1c, 0x0a, 0x17, 0x49, 0x6e,
	0x73, 0x75, 0x66, 0x66, 0x69, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x73, 0x10, 0xed, 0x27, 0x12, 0x10, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x4e,
	0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x92, 0x27, 0x12, 0x0d, 0x0a, 0x08, 0x52, 0x65,
	0x71, 0x49, 0x6e, 0x55, 0x73, 0x65, 0x10, 0x93, 0x27, 0x12, 0x13, 0x0a, 0x0e, 0x49, 0x6e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x46, 0x65, 0x65, 0x64, 0x55, 0x52, 0x49, 0x10, 0x9c, 0x27, 0x12, 0x11,
	0x0a, 0x0c, 0x46, 0x65, 0x65, 0x64, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x9d,
	0x27, 0x12, 0x16, 0x0a, 0x11, 0x46, 0x65, 0x65, 0x64, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79,
	0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x10, 0x9e, 0x27, 0x12, 0x19, 0x0a, 0x14, 0x55, 0x6e, 0x72,
	0x65, 0x63, 0x6f, 0x67, 0x6e, 0x69, 0x7a, 0x65, 0x64, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x74,
	0x78, 0x10, 0xa6, 0x27, 0x12, 0x13, 0x0a, 0x0e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0xb0, 0x27, 0x12, 0x12, 0x0a, 0x0d, 0x44, 0x61, 0x74,
	0x61, 0x62, 0x61, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0xf0, 0x2e, 0x2a, 0x3e, 0x0a,
	0x0c, 0x50, 0x65, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x12, 0x0b, 0x0a,
	0x07, 0x4e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x70,
	0x73, 0x65, 0x72, 0x74, 0x10, 0x0a, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x50, 0x65, 0x72, 0x6d, 0x61, 0x6e, 0x65, 0x6e, 0x74, 0x6c, 0x79, 0x10, 0x14, 0x32, 0x3b, 0x0a,
	0x09, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x47, 0x72, 0x70, 0x63, 0x12, 0x2e, 0x0a, 0x0c, 0x56, 0x61,
	0x75, 0x6c, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x2e, 0x76, 0x61, 0x75,
	0x6c, 0x74, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x76, 0x61, 0x75,
	0x6c, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x28, 0x01, 0x30, 0x01, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x2d, 0x73, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x2d, 0x76, 0x61, 0x75, 0x6c, 0x74,
	0x2d, 0x6c, 0x69, 0x62, 0x70, 0x32, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_vault_proto_rawDescOnce sync.Once
	file_protos_vault_proto_rawDescData = file_protos_vault_proto_rawDesc
)

func file_protos_vault_proto_rawDescGZIP() []byte {
	file_protos_vault_proto_rawDescOnce.Do(func() {
		file_protos_vault_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_vault_proto_rawDescData)
	})
	return file_protos_vault_proto_rawDescData
}

var file_protos_vault_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_protos_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protos_vault_proto_goTypes = []interface{}{
	(Const)(0),          // 0: vault.Const
	(ReqOp)(0),          // 1: vault.ReqOp
	(MsgOp)(0),          // 2: vault.MsgOp
	(StreamMode)(0),     // 3: vault.StreamMode
	(StatusCode)(0),     // 4: vault.StatusCode
	(ErrCode)(0),        // 5: vault.ErrCode
	(PeerUpdateOp)(0),   // 6: vault.PeerUpdateOp
	(*FeedReq)(nil),     // 7: vault.FeedReq
	(*OpenFeedReq)(nil), // 8: vault.OpenFeedReq
	(*EntryHeader)(nil), // 9: vault.EntryHeader
	(*Msg)(nil),         // 10: vault.Msg
	(*ReqStatus)(nil),   // 11: vault.ReqStatus
	(*ReqErr)(nil),      // 12: vault.ReqErr
	(*PubsubState)(nil), // 13: vault.PubsubState
	(*Peer)(nil),        // 14: vault.Peer
}
var file_protos_vault_proto_depIdxs = []int32{
	1,  // 0: vault.FeedReq.ReqOp:type_name -> vault.ReqOp
	8,  // 1: vault.FeedReq.OpenFeed:type_name -> vault.OpenFeedReq
	10, // 2: vault.FeedReq.NewEntry:type_name -> vault.Msg
	3,  // 3: vault.OpenFeedReq.StreamMode:type_name -> vault.StreamMode
	2,  // 4: vault.Msg.Op:type_name -> vault.MsgOp
	9,  // 5: vault.Msg.EntryHeader:type_name -> vault.EntryHeader
	11, // 6: vault.Msg.Status:type_name -> vault.ReqStatus
	12, // 7: vault.Msg.Err:type_name -> vault.ReqErr
	4,  // 8: vault.ReqStatus.Code:type_name -> vault.StatusCode
	5,  // 9: vault.ReqErr.Code:type_name -> vault.ErrCode
	14, // 10: vault.PubsubState.Peers:type_name -> vault.Peer
	6,  // 11: vault.Peer.Op:type_name -> vault.PeerUpdateOp
	7,  // 12: vault.VaultGrpc.VaultSession:input_type -> vault.FeedReq
	10, // 13: vault.VaultGrpc.VaultSession:output_type -> vault.Msg
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_protos_vault_proto_init() }
func file_protos_vault_proto_init() {
	if File_protos_vault_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_vault_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vault_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenFeedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vault_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vault_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vault_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vault_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqErr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vault_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubsubState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_vault_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_vault_proto_rawDesc,
			NumEnums:      7,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_vault_proto_goTypes,
		DependencyIndexes: file_protos_vault_proto_depIdxs,
		EnumInfos:         file_protos_vault_proto_enumTypes,
		MessageInfos:      file_protos_vault_proto_msgTypes,
	}.Build()
	File_protos_vault_proto = out.File
	file_protos_vault_proto_rawDesc = nil
	file_protos_vault_proto_goTypes = nil
	file_protos_vault_proto_depIdxs = nil
}
