name: "Build"

on:
  pull_request:
    paths-ignore:
      - "*.md"

  push:
    paths-ignore:
      - "*.md"
    branches:
      - "main"

jobs:

  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-go@v2"
        with:
          go-version: '^1.16'

      - name: "golang pkg cache"
        uses: "actions/cache@v2"
        with:
          path: "~/go/pkg/mod"
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: "linting and static analysis"
        run: "make check"

      - name: "build"
        run: "make build"

      - name: "test"
        run: "make test"
